### ISSUE TITLE
Topic Name

### ISSUE THREAD

**Issue by mbhoek** [pBouillon/MqttTopicBuilder#49]
Looks like a clean library and that you had fun building it. A little bit of feedback:
- topics must be UTF-8 encoded; maybe this is a check you can add 
- SUBSCRIBE topics are allowed wildcards (ie topic filters), but PUBLISH topics are not; at quick glance it appears that the validator always allows wildcards
The MQTT specification with more detail is here https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901107

**Comment by pBouillon** [comment]
Those are great ways of improving it, thank you very much for your feedback  !  
I will have a look at it 😄

**Comment by pBouillon** [comment]
Resolved in #50 #51 #62
